### ISSUE TITLE
MQTT publishing

### ISSUE THREAD

**Issue by wlatic** [thirug010/Virtual-Tasmota-for-Tuya-api-devices#2]
Hello,

To confirm do these devices output LWT?

Also when i've tried the default "cmnd/device/POWER1" on command its not worked, do you have another way of this being done?

The instructions I've been using in Home Assistant are:

switch:
  - platform: mqtt
    name: "Bedroom Light"
    state_topic: "stat/bedroomlight/RESULT"
    value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/bedroomlight/POWER1"
    #availability_topic: "tele/sonoff/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false

**Comment by wlatic** [comment]
@thirug010 checking to see if this should be working or not.

**Comment by thirug010** [comment]
can you send me the device config page screen shot

**Comment by thirug010** [comment]
cmnd/device/POWER1 --> in this device should be the node id, Please make sure it is nodeId

**Comment by wlatic** [comment]
![image](https://user-images.githubusercontent.com/22769520/61000492-64f49480-a312-11e9-914b-81df2f55f1c0.png)

When i toggle via Virtual Tasmota the switch responses with:
stat/bedroomlight/RESULT {"POWER1" : "ON"}
stat/bedroomlight/POWER1 ON

I can see MQTT is sending:
cmnd/bedroomlight/POWER1 ON

However I dont see this come up in the Debug Console within Virtual Tasmota, guessing it could be a username / pass mismatch or something.

**Comment by wlatic** [comment]
@thirug010 its ok has to be on the Home Assistant end.

Did some custom control via command line and its working as expected.

**Comment by thirug010** [comment]
I have uploaded the basic mqtt client (BasciMqttClient.js) use it or use ssh mqtt command to check if the message is received 

thanks 
thiru
